apiVersion: v1
kind: Service
metadata:
  name: {{ include "penpot-helm.fullname" . }}-backend
  labels:
    {{- include "penpot-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backendService.type }}
  ports:
    - port: {{ .Values.backendService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "penpot-helm.backendSelectorLabels" . | nindent 4 }}
