apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "penpot-helm.fullname" . }}-exporter
  labels:
    {{- include "penpot-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.exporterReplicaCount }}
  selector:
    matchLabels:
      {{- include "penpot-helm.exporterSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "penpot-helm.exporterSelectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "penpot-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.exporterImage.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.exporterImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 6061
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
